### ISSUE TITLE
Cannot compile Baresip with zrtp anymore

### ISSUE THREAD

**Issue by MobiSciLab** [alfredh/baresip#259]
I got below error when compiling Bareseip 0.5.3 with zrtp (it worked on 0.5.2). Can you please help check it?

modules/zrtp/zrtp.c: In function 'session_alloc':
modules/zrtp/zrtp.c:145:6: error: incompatible type for argument 3 of 'zrtp_session_init'
  s = zrtp_session_init(zrtp_global, NULL, zid,
      ^
In file included from modules/zrtp/zrtp.c:8:0:
/Users/caominhvu/Documents/workspace/SuperBaresip/baresip-android/zrtp/include/zrtp.h:475:15: note: expected 'zrtp_signaling_role_t' but argument is of type 'unsigned char *'
 zrtp_status_t zrtp_session_init( zrtp_global_t* zrtp,
               ^
modules/zrtp/zrtp.c:145:6: error: too many arguments to function 'zrtp_session_init'
  s = zrtp_session_init(zrtp_global, NULL, zid,
      ^
In file included from modules/zrtp/zrtp.c:8:0:
/Users/caominhvu/Documents/workspace/SuperBaresip/baresip-android/zrtp/include/zrtp.h:475:15: note: declared here
 zrtp_status_t zrtp_session_init( zrtp_global_t* zrtp,
               ^
modules/zrtp/zrtp.c: In function 'module_init':
modules/zrtp/zrtp.c:365:31: error: 'zrtp_config_t' has no member named 'def_cache_path'
  ret = re_snprintf(zrtp_config.def_cache_path.buffer,
                               ^
modules/zrtp/zrtp.c:366:17: error: 'zrtp_config_t' has no member named 'def_cache_path'
      zrtp_config.def_cache_path.max_length,
                 ^
modules/zrtp/zrtp.c:372:13: error: 'zrtp_config_t' has no member named 'def_cache_path'
  zrtp_config.def_cache_path.length = ret;
             ^
modules/zrtp/zrtp.c:408:47: error: 'zrtp_config_t' has no member named 'def_cache_path'
  debug("zrtp:  cache_file:  %s\n", zrtp_config.def_cache_path.buffer);
                                               ^
make[1]: *** [build-arm/modules/zrtp/zrtp.o] Error 1

**Comment by juha-h** [comment]
MobiSciLab writes:

> It is ok if i use freeswitch libzrtp. It would be great if you help
> update documents.

baresip zrtp.c has:

 *     This module is using ZRTP implementation in Freeswitch
 *     https://github.com/juha-h/libzrtp

Which documents you refer to?

-- Juha

**Comment by MobiSciLab** [comment]
I referred to this one (Readme) https://github.com/alfredh/baresip-android

**Comment by alfredh** [comment]
fixed in https://github.com/alfredh/baresip-android/commit/f83910069304c9a02a2cf678cacad27b4a44efb7
