### ISSUE TITLE
build fails - snd_htimestamp_t - asoundlib

### ISSUE THREAD

**Issue by Manawyrm** [alfredh/baresip#154]
Hi,

a git trunk build fails on the current arch-linux with the following error: 
```
  CC [M]  build-x86_64/modules/alsa/alsa.o
In file included from /usr/include/alsa/asoundlib.h:56:0,
                 from modules/alsa/alsa.c:11:
/usr/include/alsa/timer.h:108:19: error: field 'tstamp' has incomplete type
  snd_htimestamp_t tstamp; /**< Time stamp of each event */
                   ^~~~~~
make: *** [mk/mod.mk:44: build-x86_64/modules/alsa/alsa.o] Error 1
```

any ideas? 
Thanks,
Tobias

**Comment by hargut** [comment]
I can confirm this error. Just updated from Ubuntu 16.04 to 16.10, getting the same message at compile time.
Tried to get to the root of it, but had no luck so far. Either it is related to libasound2 update (1.1.0 -> 1.1.2), or eventually to the kernel update (4.4.0 -> 4.8.0).

There are some similar errors around the web, and they all suggest to include timer.h or types.h but none of these fixes worked, and types.h is included anyways at alsa.c/alsa_play.c/alsa_src.c.

**Comment by hargut** [comment]
Attached is a quick fix for alsa. What still fails is v4l2_codec with the following error message:
```
  CC [M]  build-x86_64/modules/v4l2_codec/v4l2_codec.o
In file included from modules/v4l2_codec/v4l2_codec.c:21:0:
/usr/include/linux/videodev2.h:2107:18: error: field ‘timestamp’ has incomplete type
  struct timespec   timestamp;
                  ^~~~~~~~~
mk/mod.mk:42: recipe for target 'build-x86_64/modules/v4l2_codec/v4l2_codec.o' failed
make: *** [build-x86_64/modules/v4l2_codec/v4l2_codec.o] Error 1
```
[alsa_quick_fix-patch.txt](https://github.com/alfredh/baresip/files/516498/alsa_quick_fix-patch.txt)

**Comment by alfredh** [comment]
same problem on Debian Testing (amd64).

```
ii  libc6:amd64                           2.24-3                               amd64        GNU C Library: Shared libraries
ii  libasound2:amd64                      1.1.2-1                              amd64        shared library for ALSA applications
```

can you try to add this before #include:

#define _DEFAULT_SOURCE 1

**Comment by hargut** [comment]
#define _DEFAULT_SOURCE 1 fixes the build on Ubuntu 16.10 here for all effected module files:
alsa.c
alsa_src.c
alsa_play.c
v4l2_codec.c

Thanks!

**Comment by alfredh** [comment]
thank you for reporting the issue and helping out with a solution :)

could you please also test baresip HEAD with other versions of Ubuntu and check
that it is still building ?

**Comment by hargut** [comment]
HEAD Builds fine on Ubuntu 16.04.

**Comment by RaghuSip** [comment]
I am trying to compile baresip on redhat CentOS release 5.5 (Final) version.
Linux DVRTPG010 2.6.18-194.el5xen #1 SMP Fri Apr 2 16:16:54 EDT 2010 i686 i686 i386 GNU/Linux

inside baresip dir when excuted "make" seeing below issue
  CC [M]  build-i386/modules/v4l2_codec/v4l2_codec.o
In file included from modules/v4l2_codec/v4l2_codec.c:21:
/usr/include/linux/videodev2.h:352: error: field ?timestamp? has incomplete type
/usr/include/linux/videodev2.h:461: error: expected ?=?, ?,?, ?;?, ?asm? or ?__attribute__? before ?v4l2_std_id?
/usr/include/linux/videodev2.h:544: error: expected specifier-qualifier-list before ?v4l2_std_id?
/usr/include/linux/videodev2.h:561: error: expected specifier-qualifier-list before ?v4l2_std_id?
/usr/include/linux/videodev2.h:599: error: expected specifier-qualifier-list before ?v4l2_std_id?
/usr/include/linux/videodev2.h:622: error: expected specifier-qualifier-list before ?__s64?
make: *** [build-i386/modules/v4l2_codec/v4l2_codec.o] Error 1

**Comment by RaghuSip** [comment]
#define _DEFAULT_SOURCE 1 
line is added before #include in v4l2_codec.c file
but still compilation issue is oberved
