### ISSUE TITLE
openBSD:  immintrin.h: No such file or directory

### ISSUE THREAD

**Issue by jungle-boogie** [alfredh/baresip#374]
Hi,

This might be a platform thing (running openBSD -current):

```
 CC [M]  build-x86_64/modules/pulse/player.o
  CC [M]  build-x86_64/modules/pulse/recorder.o
  LD [M]  pulse.so
  CC [M]  build-x86_64/modules/sdl/sdl.o
  CC [M]  build-x86_64/modules/sdl/util.o
  LD [M]  sdl.so
  CC [M]  build-x86_64/modules/sdl2/sdl.o
In file included from /usr/local/include/SDL2/SDL.h:38,
                 from modules/sdl2/sdl.c:7:
/usr/local/include/SDL2/SDL_cpuinfo.h:64:23: error: immintrin.h: No such file or directory
gmake: *** [mk/mod.mk:44: build-x86_64/modules/sdl2/sdl.o] Error 1
```

**Comment by alfredh** [comment]
the sdl2.so module compiles on my OpenBSD 6.2, but with some similar warnings:

```
  CC [M]  build-x86_64/modules/sdl2/sdl.o
In file included from /usr/local/include/SDL2/SDL_cpuinfo.h:53,
                 from /usr/local/include/SDL2/SDL.h:38,
                 from modules/sdl2/sdl.c:7:
/usr/include/mmintrin.h: In function '_mm_add_si64':
/usr/include/mmintrin.h:312: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
/usr/include/mmintrin.h: In function '_mm_sub_si64':
/usr/include/mmintrin.h:416: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
/usr/include/mmintrin.h: In function '_mm_sll_si64':
/usr/include/mmintrin.h:573: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
/usr/include/mmintrin.h: In function '_mm_slli_si64':
/usr/include/mmintrin.h:585: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
/usr/include/mmintrin.h: In function '_mm_srl_si64':
/usr/include/mmintrin.h:698: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
/usr/include/mmintrin.h: In function '_mm_srli_si64':
/usr/include/mmintrin.h:710: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
In file included from /usr/local/include/SDL2/SDL_cpuinfo.h:59,
                 from /usr/local/include/SDL2/SDL.h:38,
                 from modules/sdl2/sdl.c:7:
/usr/include/xmmintrin.h: In function '_mm_sad_pu8':
/usr/include/xmmintrin.h:1178: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
In file included from /usr/include/xmmintrin.h:1246,
                 from /usr/local/include/SDL2/SDL_cpuinfo.h:59,
                 from /usr/local/include/SDL2/SDL.h:38,
                 from modules/sdl2/sdl.c:7:
/usr/include/emmintrin.h: In function '_mm_movepi64_pi64':
/usr/include/emmintrin.h:713: warning: cast from function call of type 'long long int' to non-matching type 'int __vector__'
/usr/include/emmintrin.h: In function '_mm_mul_su32':
/usr/include/emmintrin.h:1094: warning: cast from function call of type 'long long unsigned int' to non-matching type 'int __vector__'
  LD [M]  sdl2.so
```

openbsd 6.2 no `immintrin.h` file.

which version of libSDL2 are you using ? can you test any other application
that is using libSDL2 and see if that is working ?

Alfred

**Comment by alfredh** [comment]
hi @jungle-boogie 

could you paste here the output of your `sdl2-config --cflags` command ?

are you still having this issue? perhaps you can also ask the SDL people
about this ?

**Comment by jungle-boogie** [comment]
Hi @alfredh,

Sorry for no reply last week.

Yes, the build still fails with the same message.

```
$ sdl2-config --cflags
-I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/X11R6/include
```

```
$ sdl2-config --version
2.0.8
```

**Comment by alfredh** [comment]
the sdl2.so module builds fine on my Debian Testing:

```
$ sdl2-config --cflags
-I/usr/include/SDL2 -D_REENTRANT

$ sdl2-config --version
2.0.8
```

```
$ make sdl2.so
  CC [M]  build-x86_64/modules/sdl2/sdl.o
  LD [M]  sdl2.so
```

```
$ dpkg -l | grep sdl2
ii  libsdl2-2.0-0:amd64                   2.0.8+dfsg1-1                           amd64        Simple DirectMedia Layer
ii  libsdl2-dev:amd64                     2.0.8+dfsg1-1                           amd64        Simple DirectMedia Layer development files
```

my SDL_config.h defines this:

```
#define HAVE_IMMINTRIN_H 1
```

and immintrin.h is located here:

```
/usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h
```

as a work-around you can try to add this in modules/sdl2/sdl.c
before including `<SDL2/SDL.h>`:

```
#define SDL_DISABLE_IMMINTRIN_H 1
```

**Comment by jungle-boogie** [comment]
Hi @alfredh,

Your work around does work. 

```
$ gmake --version
GNU Make 4.2.1
Built for x86_64-unknown-openbsd6.2
```

If you were using clang on your test openBSD machine, what compiler flags were you passing?

**Comment by jungle-boogie** [comment]
This thread talks about the update to sdl2:
https://marc.info/?l=openbsd-ports&m=151996274720191&w=2

**Comment by alfredh** [comment]
to compile with clang:

```
$ make CC=clang
```


to compile with gcc:

```
$ make CC=gcc
```

**Comment by alfredh** [comment]
@jungle-boogie could you please try to compile another
application that is using using sdl2, such as ffmpeg:

```
    git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
    cd ffmpeg
    ./configure --enable-sdl2
    make
```

if this works, then the bug is in baresip.

**Comment by jungle-boogie** [comment]
Hi @alfredh,

It'll be a few days until I can get back to this. I imagine baresip is fine. I've also received some emails from the maintainer of SDL2 for openBSD that should aide in my discovery of a possible problem.

Thanks!
