### ISSUE TITLE
avcodec module fails to build with FFmpeg 3.0

### ISSUE THREAD

**Issue by alfredh** [alfredh/baresip#114]
```
  CC [M]  build-x86_64/modules/avcodec/encode.o
modules/avcodec/encode.c:174:23: error: use of undeclared identifier 'PIX_FMT_YUV420P'; did you mean 'VID_FMT_YUV420P'?
        st->ctx->pix_fmt   = PIX_FMT_YUV420P;
                             ^~~~~~~~~~~~~~~
                             VID_FMT_YUV420P
/usr/local/include/rem/rem_vid.h:10:2: note: 'VID_FMT_YUV420P' declared here
        VID_FMT_YUV420P =  0, /* planar YUV  4:2:0   12bpp                 */
        ^
modules/avcodec/encode.c:174:23: warning: implicit conversion from enumeration type 'enum vidfmt' to different enumeration type 'enum AVPixelFormat' [-Wenum-conversion]
        st->ctx->pix_fmt   = PIX_FMT_YUV420P;
                           ~ ^~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [build-x86_64/modules/avcodec/encode.o] Error 1

```

it should be possible to use baresip with both old and new versions of FFmpeg/libav.

patches/PRs to fix this is very welcome :)
