### ISSUE TITLE
OSX 10.11 Coreaudio drop outs

### ISSUE THREAD

**Issue by sreimers** [alfredh/baresip#91]
Hi Alfred,

On the first look the play thread is running too fast and causes underruns (simple auloop test). I will investigate further and update this ticket soon. The Portaudio module on OSX works fine but has some deprecated warnings:
```
baresip[5847:27782] 14:08:22.315 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```
This is something that has to be changed in portaudio. But maybe there are other API deprecations too.

**Comment by sreimers** [comment]
I have just test the audiounit module and it works fine.

**Comment by alfredh** [comment]
the "audiounit" module works on iOS but it might work on OSX too.

last time I tested audiounit on OSX I had a problem with fixed samplingrate
of 96000 Hz. the only way to solve it was to add a re-sampler inside the module.

but if audiounit works on OSX now, maybe we should make it default instead of "coreaudio" ?

**Comment by sreimers** [comment]
Good point. In the meantime I had problems with a single audio device and only after adding this to a aggregated device it works. Maybe this could be related to your fixed samplingrate problem. So at the moment I have to test more devices and maybe someone can do some test with OSX 10.10, I upgraded my only OSX device to 10.11.

**Comment by sreimers** [comment]
Happy new year Alfred,

I`ve just released my open source project [Studio Link](https://sendegate.de/t/studio-link-plugin-release-v15-12-1-beta/2465/35)(sry german only at the moment) that based on baresip and after the first user feedback the audiounit plugin works fine on OSX too. So maybe its a good idea to set this to default now in baresip too.

**Comment by alfredh** [comment]
nice work :)

okay I will test audiounit again on a recent OSX box.

**Comment by alfredh** [comment]
Hey Sebastian,

can you please take a look at this PR:
https://github.com/alfredh/baresip/pull/98


I would like to support both "coreaudio" module and "audiounit" module for different
versions of OSX, and build them if supported by the OS.

1. in mk/modules.mk I added building of "audiounit.so" if the AudioUnit framework is present

2. in src/config.g I choose "audiounit" as default audio device, if the run-time version
  is 10.11 (El Capitan) or later


I have tested audiounit.so on my OSX machine (10.9) and it is not working, the playback part
seems to be running but the recording part reads Zero samples.

So I have no way of testing if audiounit works on 10.10 and/or 10.11 and would therefore
need some feedback from people with access to these fabulous operating systems :)

**Comment by sreimers** [comment]
Hey Alfred,

I think we have to test more and fix something. In the meantime one user has reported same problems with the mic-in https://github.com/Studio-Link/webapp/issues/38 on OSX 10.11 too.

I had no time to test, but maybe this tech-note could be interesting:

https://developer.apple.com/library/mac/technotes/tn2091/_index.html


```
    AudioDeviceID inputDevice;
    err = AudioHardwareGetProperty(kAudioHardwarePropertyDefaultInputDevice,
                                                  &size,
                                                  &inputDevice);
 
    if (err)
        return err;
 
    err =AudioUnitSetProperty(InputUnit,
                         kAudioOutputUnitProperty_CurrentDevice,
                         kAudioUnitScope_Global,
                         0,
                         &inputDevice,
                         sizeof(inputDevice));
```
This seems to be missing in the actual baresip audio unit code for mac osx.

Next weekend I can try to fix this and write a patch. But at the moment I have no audio device with the symptom.

**Comment by sreimers** [comment]
Hi Alfred,

can you test this patch with OSX 10.9

https://github.com/sreimers/baresip/commit/2fdb6a55b4c3fe143653b1813abef6f38baccc1a

**Comment by alfredh** [comment]
thanks for the patch, I have tested it on my OSX 10.9.5

- The audiounit recording still gives 0 samples with or without the patch
- The audiounit player works fine for all sample-rates, with or without the patch
- Recording with 44100 Hz (1,2ch) works fine, all other sample-rates does NOT work.

**Comment by alfredh** [comment]
I think we can enable audiounit as default for 10.10 and later

I am not so concerned about getting audiounit to work on 10.9 in this case we
can still use coreaudio.so

**Comment by sreimers** [comment]
```Recording with 44100 Hz (1,2ch) works fine, all other sample-rates does NOT work.```

I think thats the expected behavior with AUHAL Input. Its restricted IMHO to the hardware device samplerate setting.

```I am not so concerned about getting audiounit to work on 10.9 in this case we can still use coreaudio.so```

Ok.

**Comment by tuannam** [comment]
Hi Alfred,

I've tried to compile baresip-ios in El Capitan but not successful.
I got error at audiounit as below:

_modules/audiounit/recorder.c:112:19: error: use of undeclared identifier 'AudioDeviceID'
modules/audiounit/recorder.c:113:3: error: unknown type name 'AudioDeviceID'; did you mean 'AudioFileID'?
modules/audiounit/recorder.c:114:3: error: use of undeclared identifier 'AudioObjectPropertyAddress'
modules/audiounit/recorder.c:161:9: error: implicit declaration of function 'AudioObjectGetPropertyData' is invalid in C99
modules/audiounit/recorder.c:161:36: error: use of undeclared identifier 'kAudioObjectSystemObject'
modules/audiounit/recorder.c:162:6: error: use of undeclared identifier 'auAddress'_

I work of your latest source code but it looks like this module is not compatible with XCode7.0?

Thanks,
Nam.

**Comment by alfredh** [comment]
this is most likely due to this commit:

aae1708597fd5c2144f5f6a394d727a505666cb5

the added code should be valid for OSX only I guess, and not iOS.

could you add some #ifdef OSX (or similar) around the code blocks?
if it works then please make a Pull Request with your patch.

**Comment by alfredh** [comment]
added a compile-time check in audiounit, please test again ..

@sreimers can this ticket be closed now, what do you think?

**Comment by sreimers** [comment]
Yes you can close it. At the moment I prepare only a patch to set the auhal device samplerate but this has nothing todo with the orginal issue.

**Comment by alfredh** [comment]
thanks :)
